// Có 2 kiểu dữ liệu 

// (Primitive data) Dữ liệu nguyên thủy: 
// Numbers - Integers, floats  
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol constructor
// NaN
// Map


// (Non-primitive data) Không phải dữ liệu nguyên thủy
// Objects;
// Arrays;

//console.log(typeof a); //Kiem tra kieu du lieu


